write_post:
  description: >
    Generate a LinkedIn post using the following style and information:
    
    Target Audience: {target_audience}
    
    Writing Style:
    {writing_style_text}
    
    Content to transform:
    {extracted_info}
    
    Using the writing style guidelines above, create a compelling LinkedIn post that resonates with the target audience while incorporating the key information provided.
  expected_output: "A well-crafted LinkedIn post following the specified writing style"
  agent: linkedin_writer